apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-providerconfig
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: aws-secret
      key: aws-credentials.txt
