kind: Component
namespace: crossplane-system

resources:
  - gcp.provider.yaml
  - gcp.providerconfig.yaml
  - crossplane.ns.yaml

generatorOptions:
 disableNameSuffixHash: true

helmCharts:
  - name: crossplane
    repo: https://charts.crossplane.io/stable
    namespace: crossplane-system
    includeCRDs: true

