kind: Component

resources:
  - namespace.yaml
  - gcp.provider.yaml
  - gcp.providerconfig.yaml

generatorOptions:
 disableNameSuffixHash: true

secretGenerator:
- name: gcp-secret
  namespace: crossplane-system
  files:
  - gcp-credentials.json

helmCharts:
  - name: crossplane
    repo: https://charts.crossplane.io/stable
    namespace: crossplane-system
    includeCRDs: true

