kind: Component

resources:
  - namespace.yaml
  - aws.provider.yaml
  - aws.providerconfig.yaml

secretGenerator:
- name: aws-secret
  files:
  - aws-credentials.txt

helmCharts:
  - name: crossplane
    repo: https://charts.crossplane.io/stable
    namespace: crossplane-system
    includeCRDs: true

