apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.projects.pappmihaly.com`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`argocd.projects.pappmihaly.com`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
  tls:
    secretName: argocd.projects.pappmihaly.com

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd.projects.pappmihaly.com
  namespace: traefik
spec:
  dnsNames:
    - argocd.projects.pappmihaly.com
  secretName: argocd.projects.pappmihaly.com
  issuerRef:
    kind: Issuer
    name: letsencrypt-issuer
