kind: Component

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    namespace: traefik
    includeCRDs: true
    releaseName: traefik
    version: 21.1.0

resources:
  - traefik.ns.yaml

