apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: basic-bucket-asdlfkjasdlkjf12123
  labels:
    docs.crossplane.io/example: provider-gcp
spec:
  forProvider:
    location: europe-central2
    storageClass: REGIONAL
  deletionPolicy: Delete
