apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: basic-s3
  labels:
    docs.crossplane.io/example: provider-aws
spec:
  forProvider:
    region: eu-central-1
  providerConfigRef:
    name: aws-providerconfig
