apiVersion: container.gcp.upbound.io/v1beta1
kind: Cluster
metadata:
  name: pet-projects-cluster
  labels:
    gke-cluster: pet-projects-cluster
spec:
  forProvider:
    location: europe-central2-a
    initialNodeCount: 2

---

apiVersion: container.gcp.upbound.io/v1beta1
kind: NodePool
metadata:
  name: pet-projects-cluster
spec:
  forProvider:
    nodeLocations:
      - europe-central2-a
    clusterSelector:
      matchLabels:
        gke-cluster: pet-projects-cluster
    nodeConfig:
      - machineType: e2-small
        oauthScopes:
          - https://www.googleapis.com/auth/cloud-platform
        preemptible: true
    autoscaling:
      - totalMaxNodeCount: 3
