apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pet-projects-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pmihaly/personal-infra.git
    targetRevision: main
    path: overlays/main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
